# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cat": "00_core.ipynb",
         "prodpair": "00_core.ipynb",
         "append_embedding": "00_core.ipynb",
         "relation": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gngdb.github.io/relational/"

git_url = "https://github.com/gngdb/relational/tree/master/"

def custom_doc_links(name): return None
